"""Added all necessary fields for user authentication and expert profiles

Revision ID: 588169eead59
Revises: 0fe0ed9930cc
Create Date: 2025-09-26 14:37:18.873922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588169eead59'
down_revision = '0fe0ed9930cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('service', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_expert', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('social_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('social_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('social_type')
        batch_op.drop_column('social_id')
        batch_op.drop_column('is_expert')
        batch_op.drop_column('location')
        batch_op.drop_column('service')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
