"""empty message

Revision ID: 63649c42513d
Revises: ec6da9cc1d41
Create Date: 2025-09-25 16:38:39.600793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63649c42513d'
down_revision = 'ec6da9cc1d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tel_number', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint('uq_user_tel_number', ['tel_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('telnumber')

    # ### end Alembic commands ###
